# source verilog files
SYNTH_SOURCES=lc4_regfile_ss.v register.v
TOP_SYNTH_MODULE=lc4_regfile

# testbench files
TESTBENCH=testbench_lc4_regfile_ss.v
TOP_TESTBENCH_MODULE=test_regfile

include ../common/make/vivado.mk
