# source verilog files
SOURCES=lc4_divider.v
TOP_MODULE=lc4_divider

# testbench files
TESTBENCH=testbench_lc4_divider.v
TOP_TESTBENCH_MODULE=test_divider

BITSTREAM_FILENAME=div.bit

include ../common/make/vivado.mk
