# source verilog files
SYNTH_SOURCES=lc4_divider.v
TOP_SYNTH_MODULE=lc4_divider

# testbench files
TESTBENCH=testbench_lc4_divider.v
TOP_TESTBENCH_MODULE=test_divider

include ../common/make/vivado.mk
