# source verilog files
SOURCES=lc4_divider.v
TOP_MODULE=lc4_divider

# testbench files
TESTBENCH=testbench_lc4_divider.v
TOP_TESTBENCH_MODULE=test_divider

# NB: $(XDC_DIR) defined in vivado.mk
CONSTRAINTS=$(XDC_DIR)/empty.xdc

BITSTREAM_FILENAME=div.bit

include ../common/make/vivado.mk
