# source verilog files
SOURCES=rca.v
TOP_SYNTH_MODULE=rca4
TOP_IMPL_MODULE=rca4

# testbench files
TESTBENCH=rca_testbench.v
TOP_TESTBENCH_MODULE=test_adders

CONSTRAINTS=lab1.xdc 
BITSTREAM_FILENAME=rca4.bit

include ../common/make/vivado.mk
